#!/usr/bin/env bash

set -euxo pipefail

# install homebrew
if ! command -v brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# check homebrew
brew --version

# install groestlcoin
if ! command -v groestlcoind; then
  brew install groestlcoin
fi

# check groestlcoind
groestlcoind --version

# write config
if [[ ! -f ~/Library/Application\ Support/Groestlcoin/groestlcoin.conf ]]; then
  printf 'txindex=1\nsignet=1\n' > ~/Library/Application\ Support/Groestlcoin/groestlcoin.conf
fi

# start groestlcoind
if ! groestlcoin-cli getblockchaininfo; then
  brew services start groestlcoin
fi

# check groestlcoind
groestlcoin-cli getblockchaininfo | grep signet

# install ord
if ! command -v ord; then
  curl --proto '=https' --tlsv1.2 -fsLS https://raw.githubusercontent.com/Groestlcoin/ord-groestlcoin/master/install.sh | bash -s
fi

# check ord
ord --version
