[book]
title = "Ordinal Theory Handbook"
language = "en"
src = "src"

[build]
build-dir = "build"
create-missing = false
extra-watch-dirs = ["po"]

[output.html]
cname = "groestlcoin.github.io/ord-groestlcoin"
default-theme = "coal"
git-repository-url = "https://github.com/Groestlcoin/ord-groestlcoin"
preferred-dark-theme = "coal"
additional-css = ["language-picker.css"]

[output.linkcheck]

[preprocessor.gettext]
after = ["links"]
