[book]
title = "Ordinal Theory Handbook"
language = "en"
src = "src"

[build]
build-dir = "build"
create-missing = false

[output.html]
cname = "groestlcoin.github.io/ord-groestlcoin"
default-theme = "coal"
git-repository-url = "https://github.com/Groestlcoin/ord-groestlcoin"
preferred-dark-theme = "coal"

[output.linkcheck]
